name: Fuzz Testing

on:
  push:
    branches:
      - main  # Triggers the workflow when code is pushed to the main branch

jobs:
  fuzz-test:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Build the Docker image using your Dockerfile
    - name: Build Docker image
      run: |
        docker build -t fuzz-testing-image .  # Builds the Docker image based on your Dockerfile

    # Step 4: Run fuzz tests inside Docker container
    - name: Run fuzz tests in Docker container
      run: |
        docker run --rm -v $PWD:/app fuzz-testing-image python /app/fuzz.py  # Run fuzz.py inside the Docker container
